import type { Video, Category } from './types';

export const DEFAULT_HERO_VIDEO: Video = {
  id: "6aZJsxde0bMw1Xsi402i",
  title: "Spider-Verse Locomotion & Weight",
  description: "Dynamic athletic acrobatics, weight shifts, and fluid camera tracking.",
  videoUrl: "https://vz-79893c7f-720.b-cdn.net/88843fb7-a365-4028-81bf-018567aa7347/playlist.m3u8",
  thumbnailUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F6aZJsxde0bMw1Xsi402i-thumbnailUrl.jpg?alt=media&token=75b335f5-57bb-4d32-9028-87953c98ec05",
  posterUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F6aZJsxde0bMw1Xsi402i-thumbnailUrl.jpg?alt=media&token=75b335f5-57bb-4d32-9028-87953c98ec05",
  tags: ["locomotion", "weight", "acrobatics"],
  categoryIds: ["body-mechanics"],
  status: "published",
  fps: 24,
};

export const DEFAULT_LANDING_VIDEOS: Video[] = [
  DEFAULT_HERO_VIDEO,
  {
    id: "BpaxQqjgGQFGIxAN14kt",
    title: "How to Train Your Dragon - Flight & Arcs",
    description: "Creature flight arcs, wing mechanics, and deceleration physics.",
    videoUrl: "https://vz-79893c7f-720.b-cdn.net/299a8fff-3ce2-4147-b1e4-60286c1ba900/playlist.m3u8",
    thumbnailUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FBpaxQqjgGQFGIxAN14kt-thumbnailUrl.jpg?alt=media&token=ce9a558f-1f03-4b48-a8c3-31d2d1590c6b",
    posterUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FBpaxQqjgGQFGIxAN14kt-thumbnailUrl.jpg?alt=media&token=ce9a558f-1f03-4b48-a8c3-31d2d1590c6b",
    tags: ["dragon", "flight", "arcs"],
    categoryIds: ["body-mechanics"],
    status: "published",
    fps: 24,
  },
  {
    id: "6Ey58zP67WZt4uF4VUjJ",
    title: "The Incredibles - Body Mechanics & Weight",
    description: "Heavy body mechanics, anticipation, and follow-through.",
    videoUrl: "https://vz-79893c7f-720.b-cdn.net/a21246c5-6145-4b32-b597-a7dbae268659/playlist.m3u8",
    thumbnailUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F6Ey58zP67WZt4uF4VUjJ-thumbnailUrl.jpg?alt=media&token=5263a01c-15ac-45ce-bbe0-80d3932399f2",
    posterUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F6Ey58zP67WZt4uF4VUjJ-thumbnailUrl.jpg?alt=media&token=5263a01c-15ac-45ce-bbe0-80d3932399f2",
    tags: ["body-mechanics", "weight", "punch"],
    categoryIds: ["body-mechanics"],
    status: "published",
    fps: 24,
  },
  {
    id: "FgpWSTRQPyIZ4a0laT7P",
    title: "Physical Acrobatics & Locomotion",
    description: "Clean balance transfer, pivots, and core stabilization.",
    videoUrl: "https://vz-79893c7f-720.b-cdn.net/b9f1da36-b0d7-43d7-a5df-535e951650c2/playlist.m3u8",
    thumbnailUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FFgpWSTRQPyIZ4a0laT7P-thumbnailUrl.jpg?alt=media&token=45a5a29f-938e-49de-90ab-e07e243fbee3",
    posterUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FFgpWSTRQPyIZ4a0laT7P-thumbnailUrl.jpg?alt=media&token=45a5a29f-938e-49de-90ab-e07e243fbee3",
    tags: ["acrobatics", "parkour", "locomotion"],
    categoryIds: ["body-mechanics"],
    status: "published",
    fps: 24,
  },
  {
    id: "DARAnXoYG2L7DxctmfWt",
    title: "Puss In Boots - Combat Timing & Spacing",
    description: "Rapid fencing, snappy timing, and dynamic anime-inspired smears.",
    videoUrl: "https://vz-79893c7f-720.b-cdn.net/7868a062-472a-42de-a258-4f3c45c67759/playlist.m3u8",
    thumbnailUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FDARAnXoYG2L7DxctmfWt-thumbnailUrl.jpg?alt=media&token=5c9e5b7d-fcf8-40bd-b03d-4463f487b634",
    posterUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FDARAnXoYG2L7DxctmfWt-thumbnailUrl.jpg?alt=media&token=5c9e5b7d-fcf8-40bd-b03d-4463f487b634",
    tags: ["combat", "timing", "spacing"],
    categoryIds: ["combat-action"],
    status: "published",
    fps: 24,
  },
  {
    id: "03U8Lvqv20aWJUZXVUIk",
    title: "Ghost In The Shell - Cinematic Action",
    description: "2D masterpiece action choreography with precise weapon handling.",
    videoUrl: "https://vz-79893c7f-720.b-cdn.net/8ba2222a-d5b0-48c0-8dd9-94c27c81c45f/playlist.m3u8",
    thumbnailUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F03U8Lvqv20aWJUZXVUIk-thumbnailUrl.jpg?alt=media&token=e2463d62-4051-451c-a666-b9c3b30c1b24",
    posterUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F03U8Lvqv20aWJUZXVUIk-thumbnailUrl.jpg?alt=media&token=e2463d62-4051-451c-a666-b9c3b30c1b24",
    tags: ["anime", "action", "cinematic"],
    categoryIds: ["combat-action"],
    status: "published",
    fps: 24,
  },
  {
    id: "FaWdAeZlRVe1uegnbhWH",
    title: "Moana - Subtle Character Acting",
    description: "Subtle micro-expressions, breathing cadence, and weight shift.",
    videoUrl: "https://vz-79893c7f-720.b-cdn.net/56735e10-af8c-4e39-935d-58b253b8cdda/playlist.m3u8",
    thumbnailUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FFaWdAeZlRVe1uegnbhWH-thumbnailUrl.jpg?alt=media&token=db34ad6b-5912-4118-80c4-3ecea9032216",
    posterUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FFaWdAeZlRVe1uegnbhWH-thumbnailUrl.jpg?alt=media&token=db34ad6b-5912-4118-80c4-3ecea9032216",
    tags: ["acting", "facial", "dialogue"],
    categoryIds: ["acting-dialogue"],
    status: "published",
    fps: 24,
  },
  {
    id: "IE5SniMjwG1nbBeqyO4I",
    title: "The Sea Beast - Creature Locomotion",
    description: "Massive scale underwater and surface creature locomotion physics.",
    videoUrl: "https://vz-79893c7f-720.b-cdn.net/e6f75d47-6f66-4bb0-86b6-1499709bc962/playlist.m3u8",
    thumbnailUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FIE5SniMjwG1nbBeqyO4I-thumbnailUrl.jpg?alt=media&token=22659f64-9336-49e2-a61f-cafd0a0d30cc",
    posterUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FIE5SniMjwG1nbBeqyO4I-thumbnailUrl.jpg?alt=media&token=22659f64-9336-49e2-a61f-cafd0a0d30cc",
    tags: ["creature", "water", "locomotion"],
    categoryIds: ["body-mechanics"],
    status: "published",
    fps: 24,
  },
  {
    id: "0Vqxtvv5urSN7bK5dp5Q",
    title: "Tangled - Exaggerated Expression",
    description: "Disney-style broad comedic facial expressions and squash & stretch.",
    videoUrl: "https://vz-79893c7f-720.b-cdn.net/cb47d292-86da-4ec3-9746-ef841ebd31ad/playlist.m3u8",
    thumbnailUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F0Vqxtvv5urSN7bK5dp5Q-thumbnailUrl.jpg?alt=media&token=044c8dc4-9d56-4c6a-85ac-80ee037e14f2",
    posterUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F0Vqxtvv5urSN7bK5dp5Q-thumbnailUrl.jpg?alt=media&token=044c8dc4-9d56-4c6a-85ac-80ee037e14f2",
    tags: ["acting", "facial", "comedy"],
    categoryIds: ["acting-dialogue"],
    status: "published",
    fps: 24,
  },
  {
    id: "6LgFskhTr0NLEiTcLWuw",
    title: "The Mitchells vs. the Machines - Snappy Pacing",
    description: "Extreme poses held on 2s with explosive dynamic transitions.",
    videoUrl: "https://vz-79893c7f-720.b-cdn.net/c714a089-8cd5-4ea0-b3b3-c38c1ce63b25/playlist.m3u8",
    thumbnailUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F6LgFskhTr0NLEiTcLWuw-thumbnailUrl.jpg?alt=media&token=a369167f-b867-4dff-92a1-f19ad1751a98",
    posterUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F6LgFskhTr0NLEiTcLWuw-thumbnailUrl.jpg?alt=media&token=a369167f-b867-4dff-92a1-f19ad1751a98",
    tags: ["snappy", "pacing", "acting"],
    categoryIds: ["acting-dialogue"],
    status: "published",
    fps: 24,
  },
];

export const DEFAULT_LANDING_CATEGORIES: Category[] = [
  {
    id: "body-mechanics",
    title: "Body Mechanics & Weight",
    description: "Jumps, landings, lifts, parkour, and athletic balance references.",
    href: "/browse?category=body-mechanics",
    tags: ["body-mechanics", "weight", "jumps"],
    status: "published",
    imageUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2F6aZJsxde0bMw1Xsi402i-thumbnailUrl.jpg?alt=media&token=75b335f5-57bb-4d32-9028-87953c98ec05",
  },
  {
    id: "combat-action",
    title: "Combat, Stunts & Martial Arts",
    description: "Weapon choreography, boxing, martial arts, and sword swings.",
    href: "/browse?category=combat-action",
    tags: ["combat", "stunts", "martial-arts"],
    status: "published",
    imageUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FDARAnXoYG2L7DxctmfWt-thumbnailUrl.jpg?alt=media&token=5c9e5b7d-fcf8-40bd-b03d-4463f487b634",
  },
  {
    id: "acting-dialogue",
    title: "Acting, Emotion & Dialogue",
    description: "Facial expressions, gestures, pantomime, and dramatic performances.",
    href: "/browse?category=acting-dialogue",
    tags: ["acting", "emotion", "dialogue"],
    status: "published",
    imageUrl: "https://firebasestorage.googleapis.com/v0/b/aniamtion-reference.firebasestorage.app/o/migrated-thumbnails%2FFaWdAeZlRVe1uegnbhWH-thumbnailUrl.jpg?alt=media&token=db34ad6b-5912-4118-80c4-3ecea9032216",
  },
];
