import type { Video, Category } from './types';

export const DEFAULT_HERO_VIDEO: Video = {
  id: "sakugabooru-83563",
  title: "Kimetsu No Yaiba — Creature Locomotion & Debris FX",
  description: "Dynamic athletic acrobatics, creature weight shifts, and fluid arcs.",
  videoUrl: "https://www.sakugabooru.com/data/c6c3451b29890089943589b1bb0e3ebd.mp4",
  thumbnailUrl: "https://www.sakugabooru.com/data/preview/c6c3451b29890089943589b1bb0e3ebd.jpg",
  posterUrl: "https://www.sakugabooru.com/data/preview/c6c3451b29890089943589b1bb0e3ebd.jpg",
  tags: ["creature", "locomotion", "weight", "acrobatics"],
  categoryIds: ["body-mechanics", "00YSaHyKCqexOMjP3qx5"],
  status: "published",
  fps: 24,
};

export const DEFAULT_LANDING_VIDEOS: Video[] = [
  DEFAULT_HERO_VIDEO,
  {
    id: "sakugabooru-69062",
    title: "Fullmetal Alchemist — Combat & Sword Arcs",
    description: "Precision blade arcs, foot pivots, and snappy anticipation.",
    videoUrl: "https://www.sakugabooru.com/data/e0dd86863fd54cd5c06a6dead12c29e2.mp4",
    thumbnailUrl: "https://www.sakugabooru.com/data/preview/e0dd86863fd54cd5c06a6dead12c29e2.jpg",
    posterUrl: "https://www.sakugabooru.com/data/preview/e0dd86863fd54cd5c06a6dead12c29e2.jpg",
    tags: ["combat", "sword", "arcs", "fighting"],
    categoryIds: ["combat-action", "m0CyxY6mfwH1NA4cODUE"],
    status: "published",
    fps: 24,
  },
  {
    id: "sakugabooru-68923",
    title: "James Baxter — 360° Turn & Character Acting",
    description: "Masterclass volume preservation, full body squash-and-stretch, and organic rotational arcs.",
    videoUrl: "https://www.sakugabooru.com/data/1ddcfd6d99e6c6d8e9eb49ae8f2983c4.mp4",
    thumbnailUrl: "https://www.sakugabooru.com/data/preview/1ddcfd6d99e6c6d8e9eb49ae8f2983c4.jpg",
    posterUrl: "https://www.sakugabooru.com/data/preview/1ddcfd6d99e6c6d8e9eb49ae8f2983c4.jpg",
    tags: ["character-acting", "acting", "rotation", "james-baxter"],
    categoryIds: ["acting-dialogue", "7GjU9a66aYCz7Rz1tblf"],
    status: "published",
    fps: 24,
  },
  {
    id: "sakugabooru-83655",
    title: "FLCL — High Energy Impact & Character Acting",
    description: "Multi-directional debris physics, smears, and explosive character mechanics.",
    videoUrl: "https://www.sakugabooru.com/data/71bdf7ef1c4cb85d6f85ad1934aa921e.mp4",
    thumbnailUrl: "https://www.sakugabooru.com/data/preview/71bdf7ef1c4cb85d6f85ad1934aa921e.jpg",
    posterUrl: "https://www.sakugabooru.com/data/preview/71bdf7ef1c4cb85d6f85ad1934aa921e.jpg",
    tags: ["impact", "acting", "debris", "explosions"],
    categoryIds: ["combat-action", "EeIMYpkza6ffxV97C67D"],
    status: "published",
    fps: 24,
  },
  {
    id: "sakugabooru-84422",
    title: "3D Background Combat & Hair Motion",
    description: "Rapid fencing, snappy timing, dynamic camera tracking, and cloth follow-through.",
    videoUrl: "https://www.sakugabooru.com/data/a1c52c28a53458a94efbf37bbb222ab5.mp4",
    thumbnailUrl: "https://www.sakugabooru.com/data/preview/a1c52c28a53458a94efbf37bbb222ab5.jpg",
    posterUrl: "https://www.sakugabooru.com/data/preview/a1c52c28a53458a94efbf37bbb222ab5.jpg",
    tags: ["combat", "timing", "spacing", "vfx"],
    categoryIds: ["combat-action", "m0CyxY6mfwH1NA4cODUE"],
    status: "published",
    fps: 24,
  },
  {
    id: "sakugabooru-67316",
    title: "Hiroyuki Imaishi — Expressive Character Acting",
    description: "Masterclass expressive posture shifts, snappy timing, and comedic silhouette exaggeration.",
    videoUrl: "https://www.sakugabooru.com/data/11ec72f47470f08d588acd6bf100f50a.mp4",
    thumbnailUrl: "https://www.sakugabooru.com/data/preview/11ec72f47470f08d588acd6bf100f50a.jpg",
    posterUrl: "https://www.sakugabooru.com/data/preview/11ec72f47470f08d588acd6bf100f50a.jpg",
    tags: ["acting", "character-acting", "timing", "imaishi"],
    categoryIds: ["acting-dialogue", "7GjU9a66aYCz7Rz1tblf"],
    status: "published",
    fps: 24,
  },
  {
    id: "sakugabooru-69064",
    title: "Fullmetal Alchemist — VFX, Lightning & Explosions",
    description: "Elemental magic effects, shockwaves, debris scattering, and timing arcs.",
    videoUrl: "https://www.sakugabooru.com/data/1fff9324dade4765248a73abc82b9488.mp4",
    thumbnailUrl: "https://www.sakugabooru.com/data/preview/1fff9324dade4765248a73abc82b9488.jpg",
    posterUrl: "https://www.sakugabooru.com/data/preview/1fff9324dade4765248a73abc82b9488.jpg",
    tags: ["vfx", "lightning", "combat", "effects"],
    categoryIds: ["EeIMYpkza6ffxV97C67D", "JnNo18EyCB8UvqHXZvBl"],
    status: "published",
    fps: 24,
  },
  {
    id: "sakugabooru-84723",
    title: "Demon Slayer — 3D Background Combat & Fire FX",
    description: "Explosive fire arcs, blade momentum, and synchronized 3D camera pan.",
    videoUrl: "https://www.sakugabooru.com/data/dc6d4a63794315bcf793f1481578bdcd.mp4",
    thumbnailUrl: "https://www.sakugabooru.com/data/preview/dc6d4a63794315bcf793f1481578bdcd.jpg",
    posterUrl: "https://www.sakugabooru.com/data/preview/dc6d4a63794315bcf793f1481578bdcd.jpg",
    tags: ["fire", "combat", "cgi", "effects"],
    categoryIds: ["combat-action", "EeIMYpkza6ffxV97C67D"],
    status: "published",
    fps: 24,
  },
];

export const DEFAULT_LANDING_CATEGORIES: Category[] = [
  {
    id: "body-mechanics",
    title: "Body Mechanics",
    slug: "body-mechanics",
    description: "Weight, balance, athletic motion, and locomotion cycles.",
    imageUrl: "https://www.sakugabooru.com/data/preview/c6c3451b29890089943589b1bb0e3ebd.jpg",
    href: "/category/body-mechanics",
    status: "published",
    tags: [],
  },
  {
    id: "combat-action",
    title: "Combat & Action",
    slug: "fighting",
    description: "Choreography, martial arts, weapon combat, and impact frames.",
    imageUrl: "https://www.sakugabooru.com/data/preview/e0dd86863fd54cd5c06a6dead12c29e2.jpg",
    href: "/category/fighting",
    status: "published",
    tags: [],
  },
  {
    id: "acting-dialogue",
    title: "Acting & Expressions",
    slug: "character-acting",
    description: "Subtle emotion, pantomime, eye tracking, and facial expressions.",
    imageUrl: "https://www.sakugabooru.com/data/preview/1ddcfd6d99e6c6d8e9eb49ae8f2983c4.jpg",
    href: "/category/character-acting",
    status: "published",
    tags: [],
  },
  {
    id: "2d-effects",
    title: "2D VFX & Effects",
    slug: "2d-effects",
    description: "Explosions, water, fire, smoke, debris, and elemental physics.",
    imageUrl: "https://www.sakugabooru.com/data/preview/1fff9324dade4765248a73abc82b9488.jpg",
    href: "/category/2d-effects",
    status: "published",
    tags: [],
  },
];
