import type { PortfolioItem } from "./types";

export const MOCK_PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: "mock-1",
    userId: "demo-animator-1",
    authorName: "Alex Rivera",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
    title: "Cyberpunk Acrobat Jump & Roll - Blocking Pass",
    description: "Focusing on weight transfer, key poses, and silhouette readability. Working in Maya with the Azri rig.",
    type: "wip",
    wipStage: "blocking",
    mediaType: "video_url",
    mediaUrl: "https://storage.googleapis.com/aniamtion-reference.firebasestorage.app/videos/53661796-3f97-4c8a-a198-a7dd4bfef741.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80",
    tags: ["Body Mechanics", "Blocking", "3D Animation", "Physics / Weight"],
    software: ["Maya", "Blender"],
    likesCount: 42,
    viewsCount: 310,
    sortIndex: 0,
    isFeatured: true,
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 2 },
    updatedAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 2 },
  },
  {
    id: "mock-2",
    userId: "demo-animator-1",
    authorName: "Alex Rivera",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
    title: "Dramatic Monologue Dialogue - Lip Sync & Subtle Acting",
    description: "Splining pass focusing on eye darts, micro-expressions, and speech rhythm timing.",
    type: "wip",
    wipStage: "splining",
    mediaType: "video_url",
    mediaUrl: "https://storage.googleapis.com/aniamtion-reference.firebasestorage.app/videos/91f0a5c6-48d7-4956-bf1b-9b92e5331b02.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    tags: ["Acting", "Facial", "Lip Sync", "3D Animation"],
    software: ["Maya", "Substance Painter"],
    likesCount: 68,
    viewsCount: 540,
    sortIndex: 1,
    isFeatured: false,
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 5 },
    updatedAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 5 },
  },
  {
    id: "mock-3",
    userId: "demo-animator-1",
    authorName: "Alex Rivera",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
    title: "Dragon Creature Flight & Landing Polish Pass",
    description: "Quadruped/creature dynamics with wing overlap and heavy ground impact physics.",
    type: "portfolio",
    wipStage: "completed",
    mediaType: "video_url",
    mediaUrl: "https://storage.googleapis.com/aniamtion-reference.firebasestorage.app/videos/6240985f-d28b-4b4f-abe4-a3402910862c.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80",
    tags: ["Creature", "3D Animation", "Physics / Weight", "VFX / FX"],
    software: ["Maya", "Unreal Engine", "Houdini"],
    likesCount: 125,
    viewsCount: 1280,
    sortIndex: 2,
    isFeatured: false,
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 10 },
    updatedAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 10 },
  },
  {
    id: "mock-4",
    userId: "demo-animator-1",
    authorName: "Alex Rivera",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
    title: "2D Frame-by-Frame Sword Combo Action",
    description: "Rough keys drawn in ToonBoom Harmony. Testing smear frames and impact lines.",
    type: "wip",
    wipStage: "blocking",
    mediaType: "video_url",
    mediaUrl: "https://storage.googleapis.com/aniamtion-reference.firebasestorage.app/videos/ec7f25e7-74c9-48e5-b289-3a200c7146d5.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    tags: ["Combat / Action", "2D Animation", "Body Mechanics"],
    software: ["ToonBoom Harmony", "TVPaint"],
    likesCount: 89,
    viewsCount: 820,
    sortIndex: 3,
    isFeatured: false,
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 12 },
    updatedAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 12 },
  },
  {
    id: "mock-5",
    userId: "demo-animator-1",
    authorName: "Alex Rivera",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
    title: "Heavy Mech Walk & Turning Mechanics",
    description: "Testing weight distribution, foot contact stiffness, and mechanical inertia.",
    type: "portfolio",
    wipStage: "completed",
    mediaType: "video_url",
    mediaUrl: "https://storage.googleapis.com/aniamtion-reference.firebasestorage.app/videos/d6592aca-d0fb-438b-be52-05da0c7b05d0.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    tags: ["Walk Cycle", "3D Animation", "Physics / Weight"],
    software: ["Blender", "Unreal Engine"],
    likesCount: 54,
    viewsCount: 460,
    sortIndex: 4,
    isFeatured: false,
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 15 },
    updatedAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 15 },
  }
];
